<?php
/**
 * Template Part: Section — Blog Detail Content.
 *
 * Renders the TOC container, article body (the_content),
 * and social share buttons. Must be called inside the WP Loop.
 *
 * @package XanhDesignBuild
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>

<div class="article-main mx-auto" itemprop="articleBody">

	<!-- Table of Contents (auto-generated by JS) -->
	<div class="toc mb-10 bg-white p-6 md:p-8 rounded-2xl border border-dark/10 shadow-[0_8px_30px_rgba(0,0,0,0.04)]">
		<div class="toc__header flex items-center justify-between mb-2 cursor-pointer group" id="toc-toggle">
			<h3 class="font-heading font-bold text-[1.125rem] text-dark flex items-center gap-2 group-hover:text-primary transition-colors">
				<i data-lucide="list" class="w-5 h-5 text-primary"></i>
				Nội dung bài viết
			</h3>
			<button aria-label="Toggle TOC">
				<i data-lucide="chevron-down" class="w-5 h-5 text-dark/50 group-hover:text-primary transition-transform" id="toc-icon"></i>
			</button>
		</div>
		<div class="toc__body overflow-hidden transition-all duration-300" id="toc-body">
			<!-- Auto-generated via JS -->
		</div>
	</div>

	<!-- Article Body -->
	<div class="article-body prose-content font-body text-base md:text-[17px] leading-relaxed text-dark/80">
		<?php the_content(); ?>
	</div>


	<!-- Social Share -->
	<div class="social-share mt-12 pt-8 border-t border-dark/10 flex flex-wrap items-center justify-between gap-4">
		<div class="text-sm font-semibold uppercase tracking-widest text-dark/50">Chia sẻ bài viết</div>
		<div class="flex items-center gap-3">
			<!-- Facebook -->
			<a href="<?php echo esc_url( 'https://www.facebook.com/sharer/sharer.php?u=' . urlencode( get_permalink() ) ); ?>"
			   class="social-btn w-10 h-10 rounded-full border border-dark/10 flex items-center justify-center text-dark hover:bg-[#1877F2] hover:text-white hover:border-[#1877F2] transition-colors"
			   target="_blank"
			   rel="noopener noreferrer"
			   aria-label="Share on Facebook">
				<i data-lucide="facebook" class="w-4 h-4"></i>
			</a>
			<!-- Zalo (Official SDK Widget) -->
			<div class="zalo-share-button inline-block"
				 data-href="<?php echo esc_url( get_permalink() ); ?>"
				 data-oaid="<?php echo esc_attr( xanh_get_option( 'xanh_zalo_oa' ) ); ?>"
				 data-layout="1"
				 data-color="blue"
				 data-customize="true">
				<button type="button"
					class="social-btn w-10 h-10 rounded-full border border-dark/10 flex items-center justify-center text-dark hover:bg-[#0068FF] hover:text-white hover:border-[#0068FF] transition-colors"
					aria-label="Share on Zalo">
					<svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 614.501 613.667" fill="currentColor">
						<path d="M464.721,301.399c-13.984-0.014-23.707,11.478-23.944,28.312c-0.251,17.771,9.168,29.208,24.037,29.202   c14.287-0.007,23.799-11.095,24.01-27.995C489.028,313.536,479.127,301.399,464.721,301.399z" />
						<path d="M291.83,301.392c-14.473-0.316-24.578,11.603-24.604,29.024c-0.02,16.959,9.294,28.259,23.496,28.502   c15.072,0.251,24.592-10.87,24.539-28.707C315.214,313.318,305.769,301.696,291.83,301.392z" />
						<path d="M310.518,3.158C143.102,3.158,7.375,138.884,7.375,306.3s135.727,303.142,303.143,303.142   c167.415,0,303.143-135.727,303.143-303.142S477.933,3.158,310.518,3.158z M217.858,391.083   c-33.364,0.818-66.828,1.353-100.133-0.343c-21.326-1.095-27.652-18.647-14.248-36.583c21.55-28.826,43.886-57.065,65.792-85.621   c2.546-3.305,6.214-5.996,7.15-12.705c-16.609,0-32.784,0.04-48.958-0.013c-19.195-0.066-28.278-5.805-28.14-17.652   c0.132-11.768,9.175-17.329,28.397-17.348c25.159-0.026,50.324-0.06,75.476,0.026c9.637,0.033,19.604,0.105,25.304,9.789   c6.22,10.561,0.284,19.512-5.646,27.454c-21.26,28.497-43.015,56.624-64.559,84.902c-2.599,3.41-5.119,6.88-9.453,12.725   c23.424,0,44.123-0.053,64.816,0.026c8.674,0.026,16.662,1.873,19.941,11.267C237.892,379.329,231.368,390.752,217.858,391.083z    M350.854,330.211c0,13.417-0.093,26.841,0.039,40.265c0.073,7.599-2.599,13.647-9.512,17.084   c-7.296,3.642-14.71,3.028-20.304-2.968c-3.997-4.281-6.214-3.213-10.488-0.422c-17.955,11.728-39.908,9.96-56.597-3.866   c-29.928-24.789-30.026-74.803-0.211-99.776c16.194-13.562,39.592-15.462,56.709-4.143c3.951,2.619,6.201,4.815,10.396-0.053   c5.39-6.267,13.055-6.761,20.271-3.357c7.454,3.509,9.935,10.165,9.776,18.265C350.67,304.222,350.86,317.217,350.854,330.211z    M395.617,369.579c-0.118,12.837-6.398,19.783-17.196,19.908c-10.779,0.132-17.593-6.966-17.646-19.512   c-0.179-43.352-0.185-86.696,0.007-130.041c0.059-12.256,7.302-19.921,17.896-19.222c11.425,0.752,16.992,7.448,16.992,18.833   c0,22.104,0,44.216,0,66.327C395.677,327.105,395.828,348.345,395.617,369.579z M463.981,391.868   c-34.399-0.336-59.037-26.444-58.786-62.289c0.251-35.66,25.304-60.713,60.383-60.396c34.631,0.304,59.374,26.306,58.998,61.986   C524.207,366.492,498.534,392.205,463.981,391.868z" />
					</svg>
				</button>
			</div>
			<!-- Copy Link -->
			<button class="social-btn copy-link-btn w-10 h-10 rounded-full border border-dark/10 flex items-center justify-center text-dark hover:bg-dark hover:text-white transition-colors relative" aria-label="Copy Link" id="copy-link-btn">
				<i data-lucide="link" class="w-4 h-4"></i>
				<!-- Tooltip -->
				<span class="absolute -top-10 left-1/2 -translate-x-1/2 bg-dark text-white text-[10px] px-2 py-1 rounded opacity-0 pointer-events-none transition-opacity" id="copy-tooltip">Đã copy!</span>
			</button>
		</div>
	</div>

</div>
