<?php
/**
 * Template Part: Section — Blog Detail Content.
 *
 * Renders the TOC container, article body (the_content),
 * and social share buttons. Must be called inside the WP Loop.
 *
 * @package XanhDesignBuild
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>

<div class="article-main mx-auto" itemprop="articleBody">

	<!-- Table of Contents (auto-generated by JS) -->
	<div class="toc mb-10 bg-white p-6 md:p-8 rounded-2xl border border-dark/10 shadow-[0_8px_30px_rgba(0,0,0,0.04)]">
		<div class="toc__header flex items-center justify-between mb-2 cursor-pointer group" id="toc-toggle">
			<h3 class="font-heading font-bold text-[1.125rem] text-dark flex items-center gap-2 group-hover:text-primary transition-colors">
				<i data-lucide="list" class="w-5 h-5 text-primary"></i>
				Nội dung bài viết
			</h3>
			<button aria-label="Toggle TOC">
				<i data-lucide="chevron-down" class="w-5 h-5 text-dark/50 group-hover:text-primary transition-transform" id="toc-icon"></i>
			</button>
		</div>
		<div class="toc__body overflow-hidden transition-all duration-300" id="toc-body">
			<!-- Auto-generated via JS -->
		</div>
	</div>

	<!-- Article Body -->
	<div class="article-body prose-content font-body text-base md:text-[17px] leading-relaxed text-dark/80">
		<?php the_content(); ?>
	</div>

	<?php
	/* ── Inline CTA Banner (ACF → Theme Settings → Blog → Inline CTA Banner) ── */
	$show_inline = get_field( 'blog_show_inline_cta', 'option' );
	if ( $show_inline ) :
		$cta_title    = get_field( 'blog_inline_cta_title', 'option' );
		$cta_subtitle = get_field( 'blog_inline_cta_subtitle', 'option' );
		$cta_btn_text = get_field( 'blog_inline_cta_btn_text', 'option' );
		$cta_btn_url  = get_field( 'blog_inline_cta_btn_url', 'option' );
		$cta_icon     = get_field( 'blog_inline_cta_icon', 'option' );

		// Fallbacks
		$cta_title    = $cta_title    ?: 'Bạn đang gặp khó khăn trong việc tính toán dự toán dự án?';
		$cta_subtitle = $cta_subtitle ?: 'Nhận báo giá thiết kế chi tiết với sai số dưới 5% từ đội ngũ KTS XANH ngay hôm nay.';
		$cta_btn_text = $cta_btn_text ?: 'Tính Dự Toán';
		$cta_btn_url  = $cta_btn_url  ?: '/lien-he/';
		$cta_icon     = $cta_icon     ?: 'calculator';
	?>
	<div class="inline-banner my-10 bg-primary/5 border border-primary/20 p-6 md:p-8 flex flex-col md:flex-row items-center gap-6 justify-between relative overflow-hidden">
		<!-- Decorative bg icon -->
		<div class="absolute -right-10 -bottom-10 opacity-5" aria-hidden="true">
			<i data-lucide="<?php echo esc_attr( $cta_icon ); ?>" class="w-40 h-40"></i>
		</div>
		<div class="relative z-10 flex-1">
			<h4 class="font-heading font-bold text-xl text-primary mb-2"><?php echo esc_html( $cta_title ); ?></h4>
			<p class="text-sm text-dark/70 mb-0"><?php echo esc_html( $cta_subtitle ); ?></p>
		</div>
		<a href="<?php echo esc_url( $cta_btn_url ); ?>" class="btn btn--primary group relative z-10 whitespace-nowrap">
			<span><?php echo esc_html( $cta_btn_text ); ?></span>
			<i data-lucide="arrow-right" class="w-4 h-4 transition-transform duration-300 group-hover:translate-x-0.5"></i>
		</a>
	</div>
	<?php endif; ?>

	<!-- Social Share -->
	<div class="social-share mt-12 pt-8 border-t border-dark/10 flex flex-wrap items-center justify-between gap-4">
		<div class="text-sm font-semibold uppercase tracking-widest text-dark/50">Chia sẻ bài viết</div>
		<div class="flex items-center gap-3">
			<!-- Facebook -->
			<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo esc_url( rawurlencode( get_permalink() ) ); ?>"
			   class="social-btn w-10 h-10 rounded-full border border-dark/10 flex items-center justify-center text-dark hover:bg-[#1877F2] hover:text-white hover:border-[#1877F2] transition-colors"
			   target="_blank"
			   rel="noopener noreferrer"
			   aria-label="Share on Facebook">
				<i data-lucide="facebook" class="w-4 h-4"></i>
			</a>
			<!-- Zalo -->
			<a href="https://zalo.me/share?url=<?php echo esc_url( rawurlencode( get_permalink() ) ); ?>"
			   class="social-btn w-10 h-10 rounded-full border border-dark/10 flex items-center justify-center text-dark hover:bg-[#0068FF] hover:text-white hover:border-[#0068FF] transition-colors"
			   target="_blank"
			   rel="noopener noreferrer"
			   aria-label="Share on Zalo">
				<svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor"><path d="M21.543,10.662C21.67,6.01,17.47.338,11.006.338,4.542.338.34,6.01.468,10.662c.079,2.83,1.6,4.72,3.32,5.772a1.769,1.769,0,0,1,.877,1.888l-.513,2.028a1.5,1.5,0,0,0,2.152,1.63l1.879-.8a1.691,1.691,0,0,1,1.385-.054,12.356,12.356,0,0,0,1.438.225C17.47,21.362,21.67,15.688,21.543,10.662Zm-13.68,1.86a.855.855,0,0,1-.854-.853V10.133a.855.855,0,0,1,1.708,0v1.536A.855.855,0,0,1,7.863,12.522Zm2.553-.853a.855.855,0,0,1-.854.853H8.71a.855.855,0,0,1,0-1.708H9.563V9.28h-.853a.855.855,0,0,1,0-1.707h1.706a.855.855,0,0,1,.854.854V11.669Zm4.269,0a2.56,2.56,0,1,1-2.56-2.56h.853v-.854a.855.855,0,0,1,1.707,0V9.962A2.565,2.565,0,0,1,14.685,11.669Z"/></svg>
			</a>
			<!-- Copy Link -->
			<button class="social-btn copy-link-btn w-10 h-10 rounded-full border border-dark/10 flex items-center justify-center text-dark hover:bg-dark hover:text-white transition-colors relative" aria-label="Copy Link" id="copy-link-btn">
				<i data-lucide="link" class="w-4 h-4"></i>
				<!-- Tooltip -->
				<span class="absolute -top-10 left-1/2 -translate-x-1/2 bg-dark text-white text-[10px] px-2 py-1 rounded opacity-0 pointer-events-none transition-opacity" id="copy-tooltip">Đã copy!</span>
			</button>
		</div>
	</div>

</div>
